---
title: "Final_Project"
author: "Anyway team"
date: "3/22/2020"
output:
  html_document:
    toc: true
    theme: readable
    highlight: tango
    code_folding: show
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



## Downloading and Prepping the Data

```{r}
library(janitor)
library(caret)
library(C50)
library(randomForest)

#Downloading and Prepping the Data
hddata <- read.csv("framingham.csv")
summary(hddata)
str(hddata)
```

### Clean Data

```{r}
hd_mm <- as.data.frame(model.matrix(~ . -1, data = hddata))
hd_mm <- clean_names(hd_mm)
print(hd_mm)
train_ratio <- 0.5
set.seed(12345)
train_rows <- sample(1:nrow(hd_mm), train_ratio*nrow(hd_mm))

# LR and DT

hd_train_lr_dt <- hd_mm[train_rows, ]
hd_test_lr_dt <- hd_mm[-train_rows, ]

```

### Build Model
```{r}
#LR

bigmodel <- glm(ten_year_chd ~ . + .*., data = hd_train_lr_dt, family = "binomial")
#summary(bigmodel)

#stepmodel <- step(bigmodel, direction = "backward")
#DT

dtmodel <- C5.0(as.factor(ten_year_chd) ~ ., data = hd_train_lr_dt)


#rf

rfmodel <- randomForest(as.factor(ten_year_chd)~.,data=hd_train_lr_dt)

summary(rfmodel)
randomForest::varImpPlot(rfmodel)

```

### Predict Test and Calculate Confusion Matrix

```{r, cache=TRUE}
#LR
hd_lr_pred <- predict(bigmodel, hd_test_lr_dt , type = "response")
hd_lr_pred_bin <- ifelse(hd_lr_pred >= 0.5, 1, 0)

confusionMatrix(as.factor(hd_lr_pred_bin), as.factor(hd_test_lr_dt$ten_year_chd), positive = "1")
 
#DT
dt_pred <- predict(dtmodel, hd_test_lr_dt)

confusionMatrix(as.factor(dt_pred), as.factor(hd_test_lr_dt$ten_year_chd), positive = "1")

#RF

rfpred <- predict (rfmodel,  hd_test_lr_dt)
summary(rfpred)

confusionMatrix(as.factor(rfpred), as.factor( hd_test_lr_dt$ten_year_chd),positive="1")

```

