---
title: "KNN_ANN_SVM"
output: html_document
date: "2024-04-02"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### Downloading and Prepping the Data

```{r}
#Downloading and Prepping the Data
library(caret)
library(neuralnet)
library(class)
library(kernlab)

hd <- read.csv("framingham.csv", stringsAsFactors = TRUE)
str(hd)
summary(hd)

 
```

## Getting Data Ready for Analysis

```{r}
# Using model.matrix to convert all the factors to dummy variables
# We are converting all of the factors into dummy variables as the input into knn has to be numeric

hdmm <- as.data.frame(model.matrix(~.-1,hd))
str(hdmm)

# Randomize the rows in the data (shuffling the rows)
train_ratio <- 0.5
set.seed(12345)
hd_random <- hdmm[sample(nrow(hdmm)),]

#Normalize the data
normalize <- function(x) {
  return ((x - min(x)) / (max(x) - min(x)))
}

# we are going to normalize everything 
hd_norm <- as.data.frame(lapply(hd_random, normalize))
```


## Getting Train and Test Samples

```{r}
# Selects 10000 random rows for test data
set.seed(12345)
test_set <- sample(1:nrow(hd_norm), train_ratio*nrow(hdmm)) 
# Depending on R-version and computer, different rows may be selected. 
# If that happens, results are different. 

# Create a train set and test set
#First the predictors - all columns except the TenYearCHD column
hd_train <- hd_norm[-test_set, -match("TenYearCHD",names(hd_norm))]
hd_test <- hd_norm[test_set, -match("TenYearCHD",names(hd_norm))]

#Now the response (aka Labels) - only the TenYearCHD column
hd_train_labels <- hd_norm[-test_set, "TenYearCHD"]
hd_test_labels <- hd_norm[test_set, "TenYearCHD"]

```

> Now you are ready to build your ANN model. Feel free to modify the data load, cleaning and preparation code above as per your preference.

## ANN
```{r}
hd_train <- hdmm[test_set, ]
hd_test <- hdmm[-test_set, ]

simplemodel <- neuralnet(TenYearCHD ~., data = hd_train, hidden = 2)
plot(simplemodel)

# Make Prediction
hdpred <- predict(simplemodel, hd_test)
summary(hdpred)
hdbinpred <- ifelse(hdpred >= 0.5, 1, 0)

# Evaluation
confusionMatrix(as.factor(hdbinpred), as.factor(hd_test$TenYearCHD), positive = "1")
```
## KNN
```{r}
hd_train_knn_x <- hd_train
hd_train_knn_y <- hd_train_labels

hd_test_knn_x <- hd_test
hd_test_knn_y <- hd_test_labels
summary(hd_test_knn_x)
summary(hd_test_knn_y)

knn_pred <- knn(train = hd_train_knn_x, test = hd_test_knn_x, cl = hd_train_knn_y, k = 15)

confusionMatrix(as.factor(knn_pred), as.factor(hd_test_knn_y), positive = "1")

```
## SVM
```{r}
svm_train <- hd_train
svm_test <- hd_test

summary(svm_train)
hd_svm1 <- ksvm(as.factor(TenYearCHD) ~ ., data = svm_train, kernel = "vanilladot")
hd_svm2 <- ksvm(as.factor(TenYearCHD) ~ ., data = svm_train, kernel = "rbfdot")


hd_svmpred1 <- predict(hd_svm1, svm_test)
hd_svmpred2 <- predict(hd_svm2, svm_test)


summary(hd_svmpred2)
hd_svmpredbin <- ifelse(hd_svmpred2 >= 0.5, 1, 0)

#levels(as.factor(hd_svmpredbin))
#levels(as.factor(svm_test$TenYearCHD))
hd_svmpredbin[is.na(hd_svmpredbin)] <- 0 
#replace missing values with another suitable value 
#consider replacing them with another appropriate value before calculating the confusion matrix
confusionMatrix(as.factor(hd_svmpredbin), as.factor(svm_test$TenYearCHD), positive = "1")
```

